sudo: required
dist: trusty
language: node_js
python:
- '2.7'
jobs:
  include:
  - stage: Node 8
    node_js: '8.10'
    env: FUNCTION_DIR=dlq_processor TEST_FILE=test_cwl_lambda.py
  - stage: Node 8
    node_js: '8.10'
    env: FUNCTION_DIR=loggroup-lambda-connector TEST_FILE=test_loggroup_lambda_connector.py
before_install:
- sudo apt-get install python-pip
- cd $FUNCTION_DIR
- sudo pip install -r requirements.txt
script:
- npm run build
- python $TEST_FILE
env:
  global:
  - secure: sQf1PTch8trysQbH4Pwdikzxhh6pCPglyRe882+h1fW2NYUdnNrn3k0zaCE/u/K6f6Vo408Gk795A8t8RsvpzM3Ix5E7UqabfArLMkKAYUqeSxS9rd5UtG5m58srcYius+x1Nu5rrmZEUSmS1GpMZentTC7zGJx9HZWMaNh0mfK2DRYooeuWgufPWQCsciQwopiHTBgHd1I8sEGJDuqQcaKpn/B1wGEJl/0AO+Bw9SNCXIfqHyLWPXClQ8kAYs0nTcsZQlc9gVEwgDdBOSPSywsfIZ4AXnhfGil5kt7+Kp5RYtH8JnXObAycn2OndvVuFc0GupArNH/fOOA0i2ZtXvl3vHxsma4rG5/0KMYRA/y73FX59tTQ45Gaq0aySydIH6ryx7UQjG963kmLbDj2gsBGZdIJ1116cghxJUQEUNr0ikJyDE+ftUZ7LpuN7lhEvQTzfq+UEj0RJmbx2gFgkBZrtJRCGzv3IidNIsPAUmGbhlFZ+n/cFde96s0E3nN0y+C3KH6pIniar/T00g4GOUGMgClvDe+Lw4TLRZ5gDQxqiYgP3swcaQYHbg2uVOe0rCL+8MQx8CmLw36ZR3kxn73rArlcfr98hSoOCaylYIBxP83+SKNKZAxQkOspFdut8AeqJIv8DjkpT3bGgSxLZno8W7m1k5WrJYt6shkcnD4=
